version: 2.1
jobs:
  build_linux:
    docker:
      - image: circleci/golang:1.12

    working_directory: /go/src/github.com/InSitu-Software/extrapolator
    steps:
      - checkout
      - run: env GO111MODULE=on GOOS=linux GOARH=amd64 go build -a -o ./build/linux/extrapolator bin/extrapolator.go
      - store_artifacts:
          path: build
    
  build_freebsd:
    docker:
      - image: circleci/golang:1.12

    working_directory: /go/src/github.com/InSitu-Software/extrapolator
    steps:
      - checkout
      - run: env GO111MODULE=on GOOS=freebsd GOARH=amd64 go build -a -o ./build/freebsd/extrapolator bin/extrapolator.go
      - store_artifacts:
          path: build

  build_darwin:
    docker:
      - image: circleci/golang:1.12

    working_directory: /go/src/github.com/InSitu-Software/extrapolator
    steps:
      - checkout
      - run: env GO111MODULE=on GOOS=darwin GOARH=amd64 go build -a -o ./build/darwin/extrapolator bin/extrapolator.go
      - store_artifacts:
          path: build

workflows:
  build_binaries:
    jobs:
      - build_linux:
          filters:
            branches:
              only: master
      - build_freebsd:
          filters:
            branches:
              only: master      
      - build_darwin:
          filters:
            branches:
              only: master
