version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.12.2

jobs:
  build:
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          no-output-timeout: 20m
          region: AWS_REGION
          repo: extrapolator
          tag: '$CIRCLE_SHA1,$CIRCLE_BRANCH'

workflows:
  build:
    jobs:
      - build:
          context: Insitu_AWS